// File generated by FlutterFire CLI.
// TODO: Re-run `flutterfire configure` for project speak-british-english
// so apiKey / appId / messagingSenderId match the new Firebase apps.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcz4hXEOyE6dyNhSrjLVKwTLvyOCGQIds',
    appId: '1:964027440046:android:ceff4d891ad9c5e554863f',
    messagingSenderId: '964027440046',
    projectId: 'speak-british-english',
    databaseURL: 'https://speak-british-english-default-rtdb.firebaseio.com',
    storageBucket: 'speak-british-english.firebasestorage.app',
  );

  // apiKey/appId/messagingSenderId kept as-is until flutterfire configure.

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqESLPnt8jIPIJYLhbVySS-VQSkOpmRGE',
    appId: '1:964027440046:ios:78619b6a01eca95f54863f',
    messagingSenderId: '964027440046',
    projectId: 'speak-british-english',
    databaseURL: 'https://speak-british-english-default-rtdb.firebaseio.com',
    storageBucket: 'speak-british-english.firebasestorage.app',
    iosClientId: '964027440046-p32a700kkhga0o8rsrrvcs8a2q8uqo96.apps.googleusercontent.com',
    iosBundleId: 'com.learn.speak.british.english',
  );

  // apiKey/appId/messagingSenderId kept as-is until flutterfire configure.

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcalDvIxd7nPbsTEa5HF31K2gd79px4RE',
    appId: '1:964027440046:web:ddf9e9f37faba24754863f',
    messagingSenderId: '964027440046',
    projectId: 'speak-british-english',
    authDomain: 'speak-british-english.firebaseapp.com',
    databaseURL: 'https://speak-british-english-default-rtdb.firebaseio.com',
    storageBucket: 'speak-british-english.firebasestorage.app',
    measurementId: 'G-Y9SPKBH2SX',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqESLPnt8jIPIJYLhbVySS-VQSkOpmRGE',
    appId: '1:964027440046:ios:78619b6a01eca95f54863f',
    messagingSenderId: '964027440046',
    projectId: 'speak-british-english',
    databaseURL: 'https://speak-british-english-default-rtdb.firebaseio.com',
    storageBucket: 'speak-british-english.firebasestorage.app',
    iosClientId: '964027440046-p32a700kkhga0o8rsrrvcs8a2q8uqo96.apps.googleusercontent.com',
    iosBundleId: 'com.learn.speak.british.english',
  );

}