// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7EqjWjJJ41zmkLX98SdMZJ941fzla1cM',
    appId: '1:128498222438:android:2ef7264ec9b436df0534a7',
    messagingSenderId: '128498222438',
    projectId: 'bbc-listening-english',
    databaseURL: 'https://bbc-listening-english.firebaseio.com',
    storageBucket: 'bbc-listening-english.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqFQ2I7I1hJ8vEbe5xinI-PoSayWEpG2k',
    appId: '1:128498222438:ios:6a28f807827da6ea0534a7',
    messagingSenderId: '128498222438',
    projectId: 'bbc-listening-english',
    databaseURL: 'https://bbc-listening-english.firebaseio.com',
    storageBucket: 'bbc-listening-english.appspot.com',
    androidClientId: '128498222438-ajigulkv0l926j8fqh7gcb7g4psqog6o.apps.googleusercontent.com',
    iosClientId: '128498222438-hm17267tb543u524v3so193q1hqujtse.apps.googleusercontent.com',
    iosBundleId: 'com.learningenglish.studyingbbc.bbcReborn',
  );
}
