// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAly0A7Gz63plAQ2L4V-KE8t4sIHxXKMVU',
    appId: '1:666526516629:web:446e73b8882bf5cd62a29c',
    messagingSenderId: '666526516629',
    projectId: 'voa-learning-english-c75fe',
    authDomain: 'voa-learning-english-c75fe.firebaseapp.com',
    databaseURL: 'https://voa-learning-english-c75fe.firebaseio.com',
    storageBucket: 'voa-learning-english-c75fe.appspot.com',
    measurementId: 'G-8254ZCPEPE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOcuOMiBZJRHePHzjRE0PE0ot0ptFfxHw',
    appId: '1:666526516629:android:5818cf39fcf1c5a262a29c',
    messagingSenderId: '666526516629',
    projectId: 'voa-learning-english-c75fe',
    databaseURL: 'https://voa-learning-english-c75fe.firebaseio.com',
    storageBucket: 'voa-learning-english-c75fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQBmTmlrWlg4upjzp1G7QgAAby4alGd9k',
    appId: '1:666526516629:ios:43f43ea2a8302a0d62a29c',
    messagingSenderId: '666526516629',
    projectId: 'voa-learning-english-c75fe',
    databaseURL: 'https://voa-learning-english-c75fe.firebaseio.com',
    storageBucket: 'voa-learning-english-c75fe.appspot.com',
    iosBundleId: 'com.voalearningenglish.listeningskills',
  );
}
